// <auto-generated />
namespace DEMOBT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetabeaccountroleID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetabeaccountroleID));
        
        string IMigrationMetadata.Id
        {
            get { return "202110050606328_update-tabe-account-roleID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
