// <auto-generated />
namespace DEMOBT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Altr_Column_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altr_Column_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100722464_Altr_Column_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
